
* liborypy - org-file parser and code generator library for python

This project is still under development but you can already test this parser and
code generator if you want :)


** Usage

The usage of this library is very simple. Just import the =OrgPy= class and
call the constructor with a file name.

#+begin_src: python
import OrgPy from OrgPy

orgfile = OrgPy( "<PATH-TO-AN-ORG-FILE>" )
#+end_src:

Now the file is already parsed and can be generated to the desired format.
Just call the method =generate= and pass a file stream parameter and OrgPy 
does the rest. By default the =generate= method exports to =HTML=.

#+begin_src: python
import sys
orgfile.generate( sys.stdout )
#+end_src:

You want to export to a different language? No problem! OrgPy is designed 
very flexible and currently it defines an export format to =HTML= and =LaTeX=.
And it is very easy to adopted, change or even create new export formats 
for =OrgPy=.

Here is another example where a parsed org file is generated to a temporary
file with the =LaTeX= exporter. 

#+begin_src: python
import io
with io.open( "out.tex" , "w" ) as fd:
    orgfile.generate( fd, emit = OrgPy.LATEX )
#+end_src:

I will provide more export formats in the future but currently the focus is
only on the =HTML= and the =LaTeX= export format.

** Org-mode Language Support

