# 
#   Copyright (C) 2014-2021 Philipp Paulweber
#   All rights reserved.
# 
#   Developed by: Philipp Paulweber
#                 <https://github.com/ppaulweber/liborg>
# 
#   This file is part of liborg.
# 
#   liborg is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
# 
#   liborg is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License
#   along with liborg. If not, see <http://www.gnu.org/licenses/>.
# 
#   Additional permission under GNU GPL version 3 section 7
# 
#   liborg is distributed under the terms of the GNU General Public License
#   with the following clarification and special exception: Linking liborg
#   statically or dynamically with other modules is making a combined work
#   based on liborg. Thus, the terms and conditions of the GNU General
#   Public License cover the whole combination. As a special exception,
#   the copyright holders of liborg give you permission to link liborg
#   with independent modules to produce an executable, regardless of the
#   license terms of these independent modules, and to copy and distribute
#   the resulting executable under terms of your choice, provided that you
#   also meet, for each linked independent module, the terms and conditions
#   of the license of that module. An independent module is a module which
#   is not derived from or based on liborg. If you modify liborg, you
#   may extend this exception to your version of the library, but you are
#   not obliged to do so. If you do not wish to do so, delete this exception
#   statement from your version.
# 

* liborg: org-mode file parser and code generator library and more

This project is still under development but you can already test this parser and
code generator if you want :)

Currently the library contains only a Python-based implementation of the 
org-mode parser and code generator.

** Usage

The usage of this library is very simple. Just import the =libOrg= class and
call the constructor with a file name.

#+begin_src: python
import libOrg from libOrg

orgfile = libOrg( "<PATH-TO-AN-ORG-FILE>" )
#+end_src:

Now the file is already parsed and can be generated to the desired format.
Just call the method =generate= and pass a file stream parameter and *libOrg* 
does the rest. By default the =generate= method exports to =HTML=.

#+begin_src: python
import sys
orgfile.generate( sys.stdout )
#+end_src:

You want to export to a different language? No problem! *libOrg* is designed 
very flexible and currently it defines an export format to =HTML= and =LaTeX=.
And it is very easy to adopted, change or even create new export formats 
for =libOrg=.

Here is another example where a parsed org file is generated to a temporary
file with the =LaTeX= exporter. 

#+begin_src: python
import io
with io.open( "out.tex" , "w" ) as fd:
    orgfile.generate( fd, emit = libOrg.LATEX )
#+end_src:

I will provide more export formats in the future but currently the focus is
only on the =HTML= and the =LaTeX= export format.

** Org-mode Language Support

A fully list of all features is coming soon!

** Example

In the =var= folder you can find a quick example org-mode file which was translated to =HTML= and =LaTeX=. Furthermore, the LaTeX file was compiled to a PDF file.

** Copyright and License

The copyright holder of liborg is Philipp Paulweber (@ppaulweber)
and the used license of libstdhl is a [[https://www.gnu.org/licenses/gpl-3.0.html][GNU GPLv3+]]
with an additional permission ("GPL Linking Exception").
